Add "types" declaration to package.json
React95/React95 pull request #232
Opened 2021-03-09 10:19 UTC by kirkobyte

Adds a "types" declaration to the package.json file so TS projects with this as a dependency can find the type declarations

2021-03-09 11:53 UTC, ggdaltoso commented
Hi, @kirkobyte !

First of all, thanks for your contribution!

I'm not a TS expert but why do we need this declaration in the `package.json` of the root?
The published version of `@react95/core` does not have the `package.json` root.

Explaining a little more about the build process, this is what we have:

**@react95/core**: [The first build step](https://github.com/React95/React95/blob/master/packages/core/package.json#L63) will build the publish version of `@react95/core` inside the `dist` folder, containing: `csj`, `esm`, and `@types` folders:

``` 
packages/core/dist
├── @types
├── cjs
└── esm
```

This folder is what you will have in your project (or inside NPM).

After building the package, we run [`prepublishOnly`](https://docs.npmjs.com/cli/v7/using-npm/scripts) which [will generate](https://github.com/React95/React95/blob/master/scripts/prepublish.js) its `package.json` and README.md file.
Since the build process already make the `@types` folder, I do not think it is necessary to have the `@types` field inside `@react95/core` package.json's file:

```
// after running prepublishOnly

packages/core/dist
├── @types
├── README.md
├── cjs
├── esm
└── package.json
```

So, with this in mind, I would like to suggest you do `yarn build:core` on your machine and see if what we have inside  generated `packages/core/dist` folder is enough for you.

2021-03-09 12:34 UTC, kirkobyte commented
Hey, thanks for the quick response! Yeah, sorry, I'd tried it out by changing the `package.json` for @react95/core` in my `node_modules`, and didn't correctly pick the `package.json` to modify for the PR. I've fixed that up now :) 

Unfortunately Typescript won't automatically look at the `@types` folder for project dependencies, so currently using `@react95/core` in a Typescript project will result in this error:
![image](https://user-images.githubusercontent.com/6798667/110469993-9a024d00-80da-11eb-8e06-372b8a4bf1da.png)
(I'm using an unmodified Create React App set-up).

As far as I know, `@types` folders are only supported as a default if they're in the root of `node_modules`, as a way of supporting the external typings project, [DefinitleyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). (so users could separately deploy and install `@types/react95__core` if the project was written without types).

Adding `"types": "./@types/",` tells other Typescript projects how to do a type look-up for this dependency. An alternative solution would be to change the build script to output the `.d.ts` definition files to the same location as the `.js` files.

2021-03-09 12:38 UTC, ggdaltoso commented
> Unfortunately Typescript won't automatically look at the `@types` folder for project dependencies, so currently using `@react95/core` in a Typescript project will result in this error:
> ![image](https://user-images.githubusercontent.com/6798667/110469993-9a024d00-80da-11eb-8e06-372b8a4bf1da.png)
> (I'm using an unmodified Create React App set-up).
> 
> As far as I know, `@types` folders are only supported as a default if they're in the root of `node_modules`, as a way of supporting the external typings project, [DefinitleyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). (so users could separately deploy and install `@types/react95__core` if the project was written without types).

Good to know! Thanks!

2021-03-09 12:44 UTC, ggdaltoso requested changes
Just a typo suggestion, @kirkobyte

Also, I checked your commit messages and it doesn't follow [conventional commit pattern](https://www.conventionalcommits.org/en/v1.0.0/)

We use this pattern to automate our build and publish process, managing which version should be bumped. This is in our [contribute guide](https://github.com/React95/React95/blob/master/CONTRIBUTING.md#directories).

Could you please, revisit your commit messages and edit them?

We have a script to help us with this: `yarn commit`.

To publish a new version, the commit should start with `feat` or `fix`. Although this is a `chore` or `ci` thing, I would suggest you commit as `fix`.

2021-03-09 12:44 UTC, ggdaltoso commented on packages/core/package.json
> +  "types": "./@types/",
```suggestion
  "types": "@types",
```

Will this work? 💅

2021-03-09 12:48 UTC, kirkobyte commented on packages/core/package.json
> +  "types": "./@types/",
Yup! Looks like it does :)

2021-03-09 12:51 UTC, kirkobyte commented
On a slightly separate note, is there any appetite for migrating `@react95/clippy` to Typescript? I'd be happy to open a PR with the changes!
Also, could you confirm the version of `Node` you use for this project? `.nvmrc` says to use 8, but attempting to run `yarn install` with Node 8 will throw an error stating that Node 10 is expected

2021-03-09 12:54 UTC, kirkobyte commented
I've recommitted the changes using `yarn commit` :)

2021-03-09 12:55 UTC, ggdaltoso commented
> On a slightly separate note, is there any appetite for migrating @react95/clippy to Typescript? I'd be happy to open a PR with the changes!

It would be awesome to have `@react95/clippy` with TS! Feel free to contribute, man!

> Also, could you confirm the version of Node you use for this project? .nvmrc says to use 8, but attempting to run yarn install with Node 8 will throw an error stating that Node 10 is expected

For this, I don't really know! Would you like to suggest the Node version? I'm really open to suggestions on this... 😂

2021-03-09 12:55 UTC, kirkobyte commented
Ah sorry, I used `build`, I can change that to `fix` if you think that's more appropriate.

2021-03-09 12:57 UTC, kirkobyte commented
> It would be awesome to have @react95/clippy with TS! Feel free to contribute, man!

Great! I'll have a go at this!

> For this, I don't really know! Would you like to suggest the Node version? I'm really open to suggestions on this... 😂

Node 14 is in Long Term Support mode, so would make a sensible version to use now! It might make sense to change `.nvmrc` and add an `engines` field in `package.json` in a separate PR 😄

2021-03-09 13:34 UTC, ggdaltoso commented
> Ah sorry, I used `build`, I can change that to `fix` if you think that's more appropriate.

I was checking it would be a difference between `build` and `fix` but it seems to be none.

Our [`lerna` configuration](https://github.com/React95/React95/blob/master/lerna.json#L8) is skipping changes on `package.json` files and your PR has just it.

If you want to have your PR published, you will need to change [this line](https://github.com/React95/React95/blob/master/lerna.json#L13) too and also make your commit as `fix`

2021-03-09 15:03 UTC, kirkobyte commented
Great, fixed :)

2021-03-09 16:15 UTC, ggdaltoso approved these changes

2021-03-09 16:16 UTC, merged

2021-03-09 16:24 UTC, ggdaltoso commented
@all-contributors please add @kirkobyte for code

2024-01-25 03:02 UTC, naughtyGitCat commented
is there any progress? vs code still hints `npm i --save-dev @types/react95__clippy`

2024-01-30 12:07 UTC, ggdaltoso commented
There are no types for @react95/clippy package at the moment, @naughtyGitCat 
But it seems to be easy to fix. 

I'm currently working on a refactor but in the core package. If you can wait, I can do it but it might take some time for me to do this. 

It would be nice if we could have a contribution for you here. What do you think?

2024-01-31 03:05 UTC, naughtyGitCat commented
> There are no types for @react95/clippy package at the moment, @naughtyGitCat But it seems to be easy to fix.
> 
> I'm currently working on a refactor but in the core package. If you can wait, I can do it but it might take some time for me to do this.
> 
> It would be nice if we could have a contribution for you here. What do you think?

I would like to do,  but I am newbee in ts, if i have time , i would like to have some try, 😊